language: node_js
node_js:
  - node
  - lts/*
cache: yarn
before_install:
- docker pull pikadb/pika
- docker run -d -p 127.0.0.1:9221:9221 pikadb/pika  /pika/output/bin/pika -c /pika/output/conf/pika.conf
before_script:
  - yarn global add pm2
  - yarn global add typescript
script:
  - yarn lint
  - yarn build
  - yarn test-only
  # Test RedisCache with pika as backend
  - USE_PIKA=1 yarn test-only -g @rediscache
  - yarn compile
services:
  - docker
  - redis-server
git:
  quiet: true
  depth: 3